version: '3'
services:
  stove:
    image: violinwang/stove:ubuntu18.04-cuda11.4-base
    ports:
      - 15000:22
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
    stdin_open: true
