version: '3'
services:
  stove:
    image: violinwang/stove:latest
    ports:
      - 15000:22
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    tty: true
    stdin_open: true
    working_dir: /home/ustc
    volumes:
      - home:/home/ustc
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
volumes:
  home: